### ISSUE TITLE
area cm2 has incorrect names

### ISSUE THREAD

**Issue by unsol** [nosferatoy/units-converter#18]
https://github.com/nosferatoy/units-converter/blob/3c479376e7fddc4c6ffa15b1c48d1ec6cd305b56/src/units/area.js#L18

Should this be Square Centimeter(s)?

Thanks for the library!

**Comment by nosferatoy** [comment]
@unsol indeed you are correct, we are going to update it.

**Comment by nosferatoy** [comment]
It is fixed in v1.0.3
